POST http://localhost:3000/tasks
Content-Type: application/json

{
    "task": {   
        "submitter": "Kevin",
        "title": "Task3",
        "description": "Task3 description",
        "dueDate": "11/11/12",
        "priority": 1,
        "completed": false
    }
    
}

###
GET http://localhost:3000/tasks

###
POST http://localhost:3000/login
Content-Type: application/json

{    
        "username": "user",
        "password": "password"
    }


###

POST http://localhost:3000/refresh-token
Content-Type: application/json

{ "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlciIsInVzZXJuYW1lIjoidXNlciIsInBhc3N3b3JkIjoiJDJiJDEwJHlsMFNubnRtVHZ0eXlFem04VTVVMGVqakVhcDZwRHBXTnpjdE5HQ2ZxRVQ1bzdWNURWeTgyIiwiaWQiOiI1ZmIxNWMwNDQxODQ0ZjY4N2M0Yzg1N2IiLCJpYXQiOjE2MDU0NjY3NTgsImV4cCI6MTYwNTU1MzE1OCwiYXVkIjoiNWZiMTVjMDQ0MTg0NGY2ODdjNGM4NTdiIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.yhxTJ85WTs4GOGMStZQxJs9aY5d1grDRyP7vnQOdDbg"}

###

POST http://localhost:3000/register
Content-Type: application/json

{
        "name": "User3",
        "username": "user3",
        "password": "password",
        "isAdmin": true   
}

###

PATCH http://localhost:3000/5fb15c0441844f687c4c857b
Content-Type: application/json

{
    "password": "123456"
}