POST http://localhost:3000/tasks
Content-Type: application/json

{
    "task": {   
        "submitter": "Kevin",
        "title": "Task3",
        "description": "Task3 description",
        "dueDate": "11/11/12",
        "priority": 1,
        "completed": false
    }
    
}

###
GET http://localhost:3000/tasks

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "user": {    
    "username": "user2",
    "password": "password2",
    "name": "Isabelle",
    "id": 3,
    }
}

###

POST http://localhost:3000/refresh-token
Content-Type: application/json

{ "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFyaWUiLCJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiaWQiOjEsImlhdCI6MTYwNDUwMzkxOSwiZXhwIjoxNjM2MDYxNTE5LCJhdWQiOiIxIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.UR9qBCnbU_yUVNKK-GUp1zLWU3aRPFsRJYqu8Xq3-T4"}

###

POST http://localhost:3000/register
Content-Type: application/json

{ 
    "user": {
        "name": "Test2",
        "username": "user2",
        "password": "password",
        "isAdmin": false
    }
}